### ISSUE TITLE
[Bug] Absolute Paths

### ISSUE THREAD

**Issue by aaronjameslang** [rse/node-inline-assets#8]
Fails to convert absolute paths to be index-relative

```
+ parcel build src/index.html --out-dir dist/parcel
✨  Built in 574ms.

dist/parcel/src.71411525.js    946 B    139ms
dist/parcel/index.html          70 B      5ms
+ inline-assets dist/parcel/index.html dist/index.html
fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/src.71411525.js'
```

**Comment by Offirmo** [comment]
Yeah, same problem. parcel generates absolute pathes. We should have a way to specify a top dir or something like that.

**Comment by rse** [comment]
If absolute paths are generated by Parcel, this does not look like a problem of node-inline-assets. Parcel should be told to generate relative paths with an option, instead of node-inline-assets having to resolve absolute paths relative to a base/top/root directory, I think.
